theme = "light_minus"

[editor]
line-number = "relative"
scrolloff = 8
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "→"

[editor.statusline]
left = ["mode", "spinner", "spacer", "file-name"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]

[editor.lsp]
display-messages=true