#!/bin/sh

# Prompting.
setopt PROMPT_CR
setopt PROMPT_SP

# Completion
unsetopt CASE_GLOB
setopt correct                                                  # Auto correct mistakes

# History.
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt EXTENDED_HISTORY

# Directory.
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_MINUS

setopt NO_BEEP
